// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOuohjQfwqNojxH5HajQ3wMpTYwfnqwE',
    appId: '1:378299094530:web:c78b3536a3ef08df0ef91b',
    messagingSenderId: '378299094530',
    projectId: 'playgo-bcc8b',
    authDomain: 'playgo-bcc8b.firebaseapp.com',
    storageBucket: 'playgo-bcc8b.firebasestorage.app',
    measurementId: 'G-0VWZYXLZSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyAZxEXBcDW3r0ZYn8wEjkd-4zsj2kL3w',
    appId: '1:378299094530:android:0d14651d9404f0370ef91b',
    messagingSenderId: '378299094530',
    projectId: 'playgo-bcc8b',
    storageBucket: 'playgo-bcc8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE7XCtZv8KOZNHMusF46dGbDMTQEXeYNI',
    appId: '1:378299094530:ios:60a94aa3f5c0e34c0ef91b',
    messagingSenderId: '378299094530',
    projectId: 'playgo-bcc8b',
    storageBucket: 'playgo-bcc8b.firebasestorage.app',
    iosBundleId: 'com.example.playgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE7XCtZv8KOZNHMusF46dGbDMTQEXeYNI',
    appId: '1:378299094530:ios:60a94aa3f5c0e34c0ef91b',
    messagingSenderId: '378299094530',
    projectId: 'playgo-bcc8b',
    storageBucket: 'playgo-bcc8b.firebasestorage.app',
    iosBundleId: 'com.example.playgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVOuohjQfwqNojxH5HajQ3wMpTYwfnqwE',
    appId: '1:378299094530:web:e37185b50f432ec00ef91b',
    messagingSenderId: '378299094530',
    projectId: 'playgo-bcc8b',
    authDomain: 'playgo-bcc8b.firebaseapp.com',
    storageBucket: 'playgo-bcc8b.firebasestorage.app',
    measurementId: 'G-D0DG9N7L98',
  );
}
